# Generated by Django 2.2.2 on 2019-06-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190624_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineStatus',
        ),
    ]
